export const experience = [
  {
    id: 'cookie',
    company: 'cookie.rf',
    roleKey: 'experience.cookie.role',
    periodKey: 'experience.cookie.period',
    typeKey: 'experience.remote',
    url: 'https://информатик.онлайн/',
    current: true,
    bullets: 4,
  },
  {
    id: 'lookformer',
    company: 'Lookformer.ru',
    roleKey: 'experience.lookformer.role',
    periodKey: 'experience.lookformer.period',
    typeKey: 'experience.remote',
    url: 'https://lookformer.ru/',
    current: false,
    bullets: 5,
  },
  {
    id: 'neurounite',
    company: 'Neurounite',
    roleKey: 'experience.neurounite.role',
    periodKey: 'experience.neurounite.period',
    typeKey: 'experience.remote',
    url: 'https://neurounit.ai/',
    current: false,
    bullets: 4,
  },
  {
    id: 'kwork',
    company: 'Kwork',
    roleKey: 'experience.kwork.role',
    periodKey: 'experience.kwork.period',
    typeKey: 'experience.freelance',
    url: 'https://kwork.ru/user/yanhanov',
    current: true,
    bullets: 5,
  },
]

